# @formatter:off
"""
This module was generated by asynchron application, see https://github.com/zerlok/asynchron

Config          docs/services/scheduler/asyncapi.yaml
Created at      2022-02-08T07:00:34
Author          zerlok

"""











# @formatter:on
